#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
   --- [PSUEDOCODE] ---

   while true:
   if centerLineFollower detects line:
   move_forwards()
   else if leftLineFollower detects line:
   turn_left()
else:
turn right

--- [PSUEDOCODE] ---


*/

//Basically got this value by moving a piece of tape over the sensors a couple of times and averaged the measurements
static const int threshold = 500;
static const int LEFT = -1;
static const int RIGHT = 1;

int checkButtonSequence()
{
  if (vexRT[Btn7L] && vexRT[Btn7D])
        return 1;
  return 0;
}

int move(int speed) {

    motor[leftMotor] = speed;
    motor[rightMotor] = speed;

    return checkButtonSequence();
}

void wait(int milliseconds) {
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;

    wait1Msec(milliseconds);
}

void turn(int direction, int speed) {
    if (direction == LEFT) {
        motor[rightMotor] = speed;
        motor[leftMotor] = 0;
    }
    else {
        motor[rightMotor] = 0;
        motor[leftMotor] = speed;
    }
}

task main()
{
    while (1) {
        if (checkButtonSequence())
            break;
        if (SensorValue[rightLineFollower] > threshold) {
            turn(RIGHT, 70);
        }
        if (SensorValue[centerLineFollower] > threshold) {
            int exitcode = move(40);

            if (exitcode)
                break;
        }
        if (SensorValue[leftLineFollower] > threshold) {
            turn(LEFT, 70);
        }

    }
}
